### ISSUE TITLE
Milestone: Account Server

### ISSUE THREAD

**Issue by walkah** [fission-codes/fission-server#19]
All REST endpoints should be under `/v4/` as a prefix

- [ ] Configuration management: https://crates.io/crates/config
- [ ] Rust structure for Workspaces (separate crates)
- [ ] Database layer: deisel vs sqlx 
- [ ] Account table (did + email)
- [ ] Generate a UCAN (using rs-ucan)
- [ ] Endpoint: user registration (provides a UCAN)

Goal:
Setup of a minimal account server. Users can register an account which they can prove with the UCAN they received from the registration endpoint. That UCAN will be usable with other services that will later be added to this repo as a separate crate. 

Crates idea:
To start we want to basically take the current fission server (the Haskell one) and divide it into multiple crates, as explained in the talk post: https://talk.fission.codes/t/components-of-the-new-fission-server/4247#the-fission-server-6

From there these pieces/crates can grow into more elaborate "products", such as the [Volumes concept](https://talk.fission.codes/t/volumes-a-wnfs-storage-service/4384).

**Comment by pinkforest** [comment]
I'm going to supercede by re-organising and split this issue for MVP as discussed with @bdehaynin
