### ISSUE TITLE
Fission server tasks breakdown

### ISSUE THREAD

**Issue by bdehaynin** [fission-codes/fission-server#25]
_All lists in this issue are non-exhaustive, feel free to add new entries and order them by priority._

### Preliminary Questions
- What are our objectives for the next 6 months?
   - **Build a new Fission server stack that's written in Rust
      so we can reuse and benefit from other Rust libraries**,
      such as rs-ucan, rs-wnfs, rs-awake, etc.
   - Upgrade to the new UCANs across the ecosystem.
   - Passkey support, server needs to understand ECDSA signed UCANs.
- What dependencies does the Fission Server have?
  - Rust language
  - [rs-ucan](https://github.com/ucan-wg/rs-ucan)
  - [CAR Mirror](https://github.com/fission-codes/spec/tree/main/car-pool/car-mirror), optional, but better sooner than later.
     Fast short-term solution here is to upload CAR files via HTTP,
     where the calculation of what to upload is done in ODD.js
- What is a Fission account?
     A Fission account is an account registered on our Account Service
     which has an email address. If a DID is registered but without an email
     it is considered an app-owned-login.
- How will we publish apps?
     1. The app developer registers a Fission account.
     2. They add their app to their file system and publishes it.
     3. The app is now already accessible through the IPFS gateway.
     4. If they used the DNS naming service, it'll be available at a domain name.

### Research 
What topics still need to be investigated?
- [x] What exactly are the interactions with ODD.js?
- [x] What is a Fission account?
- [ ] #114
- [ ] #112
- [ ] #111
- [ ] #110

### Tasks to breakdown and prioritize
**Set higher priority for tasks that are needed to complete [Collector](https://talk.fission.codes/t/fil-devgrant-proposal-collector-mobile-wallet-client/3774)**

Boxes for quick reorder:
- [x] **Organisation mono repo**
  - [x] Configuration management: https://crates.io/crates/config
  - [x] Rust structure for Workspaces (separate crates)
- [x] **UCANs**
  - [x] Integrate rs-ucan
  - [x] Ability to decode a DID, extract the public key and validate a UCAN
  - [x] Support for various key types: ED25519, RSA, ECDSA (for passkeys) 
- [ ] **Account service**
  - [x] Database layer: deisel
  - [x] Account DB table (DID, email)
  - [x] Endpoint: user registration (~~provides a UCAN~~)
  - [ ] #103
  - [ ] #104
- [ ] **Channel service**
  - [ ] #105
- [ ] **Storage service**
  - [ ] #106
  - [ ] ~~Endpoint: Download a block (requires UCAN)~~
  - [ ] ~~Endpoint: Export a DAG by downloading a CAR file (requires UCAN)~~
  - [ ] ~~Endpoint: Import a DAG by uploading a CAR file (requires UCAN)~~
  - [ ] #107

Goals for MVP: 
- [x] Signups
- [ ] Ability to register DNS
- [ ] DIDs + UCANs

### Milestones

1. MVP
    - July 31st
2.  CAR Mirror integration

Past this - discover process with the ODD sdk, work on the dependencies, etc

### Visual Roadmap
[Figma](https://www.figma.com/file/x68vWbP7aNXjPblcPOE0L2/Fission-Server-Roadmap?node-id=0%3A1&t=U1B7fAk6P1Y9gHaV-1)

### Documentation to write
- [ ] #114
- [ ] #112
- [ ] #111
- [ ] #110

Resources:
- [Components of the new Fission Server](https://talk.fission.codes/t/components-of-the-new-fission-server/4247#the-fission-server-6)
- https://talk.fission.codes/t/context-for-a-very-odd-server/4484
- https://talk.fission.codes/t/fission-server-meeting-notes-ipfs-thing/4568
- [UCAN and UX flows in Figma](https://www.figma.com/file/YNR1XdOGkDNyGFPziQNIpY/Fission-Accounts?node-id=0-1&t=5j5iDDiu0XCtT24X-0)
- https://crates.io/crates/diesel-async

**Comment by expede** [comment]
https://talk.fission.codes/uploads/default/optimized/2X/6/6a9e41fde8ef63d6b66db0a3b4a0ea62ea8d4e16_2_360x1000.png

**Comment by therealjeffg** [comment]
Zeeshan: "use async diesel"
